/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./env.d.ts --include-runtime=false` (hash: c85ca00c500dbbe35e42921163ec47b9)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "WebsocketServer" | "CallbreakEngine" | "FishEngine" | "WordleEngine" | "SplendorEngine";
	}
	interface Env {
		SESSION_KV: KVNamespace;
		WEBAUTHN_KV: KVNamespace;
		WORDLE_KV: KVNamespace;
		CALLBREAK_KV: KVNamespace;
		FISH_KV: KVNamespace;
		SPLENDOR_KV: KVNamespace;
		WSS: DurableObjectNamespace<import("./src/worker").WebsocketServer>;
		CALLBREAK_DO: DurableObjectNamespace<import("./src/worker").CallbreakEngine>;
		FISH_DO: DurableObjectNamespace<import("./src/worker").FishEngine>;
		WORDLE_DO: DurableObjectNamespace<import("./src/worker").WordleEngine>;
		SPLENDOR_DO: DurableObjectNamespace<import("./src/worker").SplendorEngine>;
		DB: D1Database;
	}
}
interface Env extends Cloudflare.Env {}
