/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./env.d.ts --include-runtime=false` (hash: a84a929441607fd3c358746bd2285179)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "WebsocketServer" | "CallbreakEngine" | "FishEngine" | "WordleEngine";
	}
	interface Env {
		SESSION_KV: KVNamespace;
		WEBAUTHN_KV: KVNamespace;
		WORDLE_KV: KVNamespace;
		CALLBREAK_KV: KVNamespace;
		FISH_KV: KVNamespace;
		APP_NAME: "stairway";
		WEBAUTHN_RP_ID: string;
		AUTH_SECRET_KEY: string;
		WEBAUTHN_ORIGIN: string;
		WSS: DurableObjectNamespace<import("./src/worker").WebsocketServer>;
		CALLBREAK_DO: DurableObjectNamespace<import("./src/worker").CallbreakEngine>;
		FISH_DO: DurableObjectNamespace<import("./src/worker").FishEngine>;
		WORDLE_DO: DurableObjectNamespace<import("./src/worker").WordleEngine>;
		DB: D1Database;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_NAME" | "WEBAUTHN_RP_ID" | "AUTH_SECRET_KEY" | "WEBAUTHN_ORIGIN">> {}
}
