/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./env.d.ts --include-runtime=false` (hash: de68f11e8dc99eba7d7cbc6830940628)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "TicTacToeEngine" | "CallbreakEngine" | "SplendorEngine" | "FishEngine" | "KingdominoEngine" | "WordleEngine";
	}
	interface Env {
		DB: D1Database;
		AUTH_SECRET: string;
		TICTACTOE_ENGINE: DurableObjectNamespace<import("./src/server").TicTacToeEngine>;
		CALLBREAK_ENGINE: DurableObjectNamespace<import("./src/server").CallbreakEngine>;
		SPLENDOR_ENGINE: DurableObjectNamespace<import("./src/server").SplendorEngine>;
		FISH_ENGINE: DurableObjectNamespace<import("./src/server").FishEngine>;
		KINGDOMINO_ENGINE: DurableObjectNamespace<import("./src/server").KingdominoEngine>;
		WORDLE_ENGINE: DurableObjectNamespace<import("./src/server").WordleEngine>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_SECRET">> {}
}
