/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./env.d.ts --include-runtime=false` (hash: 9bda3208273bea665c869dd4ba5ead85)
declare namespace Cloudflare {
	interface Env {
		DB: D1Database;
		AUTH_SECRET: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_SECRET">> {}
}
