/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./env.d.ts --include-runtime=false` (hash: e0bf246ccf9e5702eba54c6c28013594)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "SyncServer";
	}
	interface Env {
		DB: D1Database;
		AUTH_SECRET: string;
		SYNC_SERVER: DurableObjectNamespace<import("./src/server").SyncServer>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_SECRET">> {}
}
