import tsPlugin from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import importPlugin from "eslint-plugin-import-x";

const client = [
	"src/routes/**",
	"src/main.*",
	"src/routeTree.*",
	"src/shared/ui/**",
	"src/auth/client/**",
	"src/games/*/client/**"
];

const server = [
	"src/platform/**",
	"src/auth/server/**",
	"src/games/*/server/**",
	"src/worker.*"
];

const shared = [
	"src/api.*",
	"src/client.*",
	"src/auth/shared/**",
	"src/games/*/shared/**",
	"src/shared/cards/**",
	"src/shared/swish/**",
	"src/shared/utils/**"
];

export default [
	{
		// Generated by the TanStack Router plugin — not authored by hand.
		ignores: [ "src/routeTree.gen.ts" ]
	},
	{
		files: [ "**/*.ts", "**/*.tsx" ],
		languageOptions: {
			parser: tsParser,
			parserOptions: { ecmaFeatures: { jsx: true } }
		},
		plugins: { "import-x": importPlugin, "@typescript-eslint": tsPlugin },
		settings: {
			"import-x/resolver": {
				typescript: { project: "./tsconfig.json" }
			},
			// Treat the "@/" path alias as internal so import-x/order groups it apart from npm packages.
			"import-x/internal-regex": "^@/"
		},
		rules: {
			// No explicit return type annotations on function implementations — let TypeScript infer.
			// Type predicates / assertion signatures (`x is T`, `asserts x`) are exempt: they cannot
			// be inferred. Type-level declarations (interface method signatures) are also not matched.
			"no-restricted-syntax": [
				"error",
				{
					selector: "FunctionDeclaration[returnType][returnType.typeAnnotation.type!='TSTypePredicate']",
					message: "Explicit return type annotations are not allowed; let TypeScript infer the return type."
				},
				{
					selector: "FunctionExpression[returnType][returnType.typeAnnotation.type!='TSTypePredicate']",
					message: "Explicit return type annotations are not allowed; let TypeScript infer the return type."
				},
				{
					selector: "ArrowFunctionExpression[returnType][returnType.typeAnnotation.type!='TSTypePredicate']",
					message: "Explicit return type annotations are not allowed; let TypeScript infer the return type."
				}
			],
			// All local ts/tsx imports must carry their file extension (npm packages are exempt).
			"import-x/extensions": [ "error", "ignorePackages", { checkTypeImports: true } ],
			// Ban relative imports — use the "@/" alias instead.
			"no-restricted-imports": [
				"error", {
					patterns: [
						{
							regex: "^\\.\\.?/",
							message: "Relative imports are not allowed. Use the \"@/\" path alias instead."
						}
					]
				}
			],
			// Split mixed type/value imports into separate `import type` / `import` statements.
			"@typescript-eslint/consistent-type-imports": [
				"error", {
					prefer: "type-imports",
					fixStyle: "separate-type-imports"
				}
			],
			// Group imports (external → internal) with a blank line between groups.
			"import-x/order": [
				"error", {
					groups: [ [ "builtin", "external" ], "internal" ],
					"newlines-between": "always"
				}
			],
			"import-x/no-restricted-paths": [
				"error", {
					zones: [
						{
							target: client,
							from: server,
							message: "Client code must not import server-only code."
						},
						{
							target: server,
							from: client,
							message: "Server code must not import client-only code."
						},
						{
							target: shared,
							from: [ ...client, ...server ],
							message: "Shared code must not import client- or server-only code."
						}
					]
				}
			]
		}
	}
];
