import { getAuthInfo } from "@stairway/api/auth";
import { montserrat, Toaster } from "@stairway/components/base";
import { LoginButton, Navbar } from "@stairway/components/main";

import type { Metadata } from "next";
import type { ReactNode } from "react";

import "./globals.css";

export const metadata: Metadata = {
	title: "Stairway",
	description: "Generated by create next app"
};

export default async function RootLayout( { children }: Readonly<{ children: ReactNode; }> ) {
	const authInfo = await getAuthInfo();
	return (
		<html lang="en">
		<body className={ `${ montserrat.className }` }>
		<main className="flex min-h-screen flex-col bg-background">
			<Navbar/>
			<div className={ "px-3 md:px-5 lg:mt-44 xl:mt-48 md:mt-40 mt-36" }>
				{ !authInfo && <LoginButton/> }
				{ children }
			</div>
			<Toaster expand richColors/>
		</main>
		</body>
		</html>
	);
}
