/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./types/env.d.ts --include-runtime false` (hash: dbbaad2656624a290c839bbb7f93101c)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../src/worker");
	}
	interface Env {
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
