/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as IndexImport } from './routes/index'
import { Route as WordleIndexImport } from './routes/wordle.index'
import { Route as LiteratureIndexImport } from './routes/literature.index'
import { Route as CallbreakIndexImport } from './routes/callbreak.index'
import { Route as WordleGameIdImport } from './routes/wordle.$gameId'
import { Route as LiteratureGameIdImport } from './routes/literature.$gameId'
import { Route as CallbreakGameIdImport } from './routes/callbreak.$gameId'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WordleIndexRoute = WordleIndexImport.update({
  path: '/wordle/',
  getParentRoute: () => rootRoute,
} as any)

const LiteratureIndexRoute = LiteratureIndexImport.update({
  path: '/literature/',
  getParentRoute: () => rootRoute,
} as any)

const CallbreakIndexRoute = CallbreakIndexImport.update({
  path: '/callbreak/',
  getParentRoute: () => rootRoute,
} as any)

const WordleGameIdRoute = WordleGameIdImport.update({
  path: '/wordle/$gameId',
  getParentRoute: () => rootRoute,
} as any)

const LiteratureGameIdRoute = LiteratureGameIdImport.update({
  path: '/literature/$gameId',
  getParentRoute: () => rootRoute,
} as any)

const CallbreakGameIdRoute = CallbreakGameIdImport.update({
  path: '/callbreak/$gameId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/callbreak/$gameId': {
      id: '/callbreak/$gameId'
      path: '/callbreak/$gameId'
      fullPath: '/callbreak/$gameId'
      preLoaderRoute: typeof CallbreakGameIdImport
      parentRoute: typeof rootRoute
    }
    '/literature/$gameId': {
      id: '/literature/$gameId'
      path: '/literature/$gameId'
      fullPath: '/literature/$gameId'
      preLoaderRoute: typeof LiteratureGameIdImport
      parentRoute: typeof rootRoute
    }
    '/wordle/$gameId': {
      id: '/wordle/$gameId'
      path: '/wordle/$gameId'
      fullPath: '/wordle/$gameId'
      preLoaderRoute: typeof WordleGameIdImport
      parentRoute: typeof rootRoute
    }
    '/callbreak/': {
      id: '/callbreak/'
      path: '/callbreak'
      fullPath: '/callbreak'
      preLoaderRoute: typeof CallbreakIndexImport
      parentRoute: typeof rootRoute
    }
    '/literature/': {
      id: '/literature/'
      path: '/literature'
      fullPath: '/literature'
      preLoaderRoute: typeof LiteratureIndexImport
      parentRoute: typeof rootRoute
    }
    '/wordle/': {
      id: '/wordle/'
      path: '/wordle'
      fullPath: '/wordle'
      preLoaderRoute: typeof WordleIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/callbreak/$gameId': typeof CallbreakGameIdRoute
  '/literature/$gameId': typeof LiteratureGameIdRoute
  '/wordle/$gameId': typeof WordleGameIdRoute
  '/callbreak': typeof CallbreakIndexRoute
  '/literature': typeof LiteratureIndexRoute
  '/wordle': typeof WordleIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/callbreak/$gameId': typeof CallbreakGameIdRoute
  '/literature/$gameId': typeof LiteratureGameIdRoute
  '/wordle/$gameId': typeof WordleGameIdRoute
  '/callbreak': typeof CallbreakIndexRoute
  '/literature': typeof LiteratureIndexRoute
  '/wordle': typeof WordleIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/callbreak/$gameId': typeof CallbreakGameIdRoute
  '/literature/$gameId': typeof LiteratureGameIdRoute
  '/wordle/$gameId': typeof WordleGameIdRoute
  '/callbreak/': typeof CallbreakIndexRoute
  '/literature/': typeof LiteratureIndexRoute
  '/wordle/': typeof WordleIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/callbreak/$gameId'
    | '/literature/$gameId'
    | '/wordle/$gameId'
    | '/callbreak'
    | '/literature'
    | '/wordle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/callbreak/$gameId'
    | '/literature/$gameId'
    | '/wordle/$gameId'
    | '/callbreak'
    | '/literature'
    | '/wordle'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/callbreak/$gameId'
    | '/literature/$gameId'
    | '/wordle/$gameId'
    | '/callbreak/'
    | '/literature/'
    | '/wordle/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  CallbreakGameIdRoute: typeof CallbreakGameIdRoute
  LiteratureGameIdRoute: typeof LiteratureGameIdRoute
  WordleGameIdRoute: typeof WordleGameIdRoute
  CallbreakIndexRoute: typeof CallbreakIndexRoute
  LiteratureIndexRoute: typeof LiteratureIndexRoute
  WordleIndexRoute: typeof WordleIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  CallbreakGameIdRoute: CallbreakGameIdRoute,
  LiteratureGameIdRoute: LiteratureGameIdRoute,
  WordleGameIdRoute: WordleGameIdRoute,
  CallbreakIndexRoute: CallbreakIndexRoute,
  LiteratureIndexRoute: LiteratureIndexRoute,
  WordleIndexRoute: WordleIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/settings",
        "/callbreak/$gameId",
        "/literature/$gameId",
        "/wordle/$gameId",
        "/callbreak/",
        "/literature/",
        "/wordle/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/callbreak/$gameId": {
      "filePath": "callbreak.$gameId.tsx"
    },
    "/literature/$gameId": {
      "filePath": "literature.$gameId.tsx"
    },
    "/wordle/$gameId": {
      "filePath": "wordle.$gameId.tsx"
    },
    "/callbreak/": {
      "filePath": "callbreak.index.tsx"
    },
    "/literature/": {
      "filePath": "literature.index.tsx"
    },
    "/wordle/": {
      "filePath": "wordle.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
