/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WordleIndexRouteImport } from './routes/wordle/index'
import { Route as TictactoeIndexRouteImport } from './routes/tictactoe/index'
import { Route as SplendorIndexRouteImport } from './routes/splendor/index'
import { Route as KingdominoIndexRouteImport } from './routes/kingdomino/index'
import { Route as FishIndexRouteImport } from './routes/fish/index'
import { Route as CallbreakIndexRouteImport } from './routes/callbreak/index'
import { Route as WordleGameIdRouteImport } from './routes/wordle/$gameId'
import { Route as TictactoeGameIdRouteImport } from './routes/tictactoe/$gameId'
import { Route as SplendorGameIdRouteImport } from './routes/splendor/$gameId'
import { Route as KingdominoGameIdRouteImport } from './routes/kingdomino/$gameId'
import { Route as FishGameIdRouteImport } from './routes/fish/$gameId'
import { Route as CallbreakGameIdRouteImport } from './routes/callbreak/$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordleIndexRoute = WordleIndexRouteImport.update({
  id: '/wordle/',
  path: '/wordle/',
  getParentRoute: () => rootRouteImport,
} as any)
const TictactoeIndexRoute = TictactoeIndexRouteImport.update({
  id: '/tictactoe/',
  path: '/tictactoe/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplendorIndexRoute = SplendorIndexRouteImport.update({
  id: '/splendor/',
  path: '/splendor/',
  getParentRoute: () => rootRouteImport,
} as any)
const KingdominoIndexRoute = KingdominoIndexRouteImport.update({
  id: '/kingdomino/',
  path: '/kingdomino/',
  getParentRoute: () => rootRouteImport,
} as any)
const FishIndexRoute = FishIndexRouteImport.update({
  id: '/fish/',
  path: '/fish/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbreakIndexRoute = CallbreakIndexRouteImport.update({
  id: '/callbreak/',
  path: '/callbreak/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordleGameIdRoute = WordleGameIdRouteImport.update({
  id: '/wordle/$gameId',
  path: '/wordle/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const TictactoeGameIdRoute = TictactoeGameIdRouteImport.update({
  id: '/tictactoe/$gameId',
  path: '/tictactoe/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const SplendorGameIdRoute = SplendorGameIdRouteImport.update({
  id: '/splendor/$gameId',
  path: '/splendor/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const KingdominoGameIdRoute = KingdominoGameIdRouteImport.update({
  id: '/kingdomino/$gameId',
  path: '/kingdomino/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const FishGameIdRoute = FishGameIdRouteImport.update({
  id: '/fish/$gameId',
  path: '/fish/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbreakGameIdRoute = CallbreakGameIdRouteImport.update({
  id: '/callbreak/$gameId',
  path: '/callbreak/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callbreak/$gameId': typeof CallbreakGameIdRoute
  '/fish/$gameId': typeof FishGameIdRoute
  '/kingdomino/$gameId': typeof KingdominoGameIdRoute
  '/splendor/$gameId': typeof SplendorGameIdRoute
  '/tictactoe/$gameId': typeof TictactoeGameIdRoute
  '/wordle/$gameId': typeof WordleGameIdRoute
  '/callbreak/': typeof CallbreakIndexRoute
  '/fish/': typeof FishIndexRoute
  '/kingdomino/': typeof KingdominoIndexRoute
  '/splendor/': typeof SplendorIndexRoute
  '/tictactoe/': typeof TictactoeIndexRoute
  '/wordle/': typeof WordleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callbreak/$gameId': typeof CallbreakGameIdRoute
  '/fish/$gameId': typeof FishGameIdRoute
  '/kingdomino/$gameId': typeof KingdominoGameIdRoute
  '/splendor/$gameId': typeof SplendorGameIdRoute
  '/tictactoe/$gameId': typeof TictactoeGameIdRoute
  '/wordle/$gameId': typeof WordleGameIdRoute
  '/callbreak': typeof CallbreakIndexRoute
  '/fish': typeof FishIndexRoute
  '/kingdomino': typeof KingdominoIndexRoute
  '/splendor': typeof SplendorIndexRoute
  '/tictactoe': typeof TictactoeIndexRoute
  '/wordle': typeof WordleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callbreak/$gameId': typeof CallbreakGameIdRoute
  '/fish/$gameId': typeof FishGameIdRoute
  '/kingdomino/$gameId': typeof KingdominoGameIdRoute
  '/splendor/$gameId': typeof SplendorGameIdRoute
  '/tictactoe/$gameId': typeof TictactoeGameIdRoute
  '/wordle/$gameId': typeof WordleGameIdRoute
  '/callbreak/': typeof CallbreakIndexRoute
  '/fish/': typeof FishIndexRoute
  '/kingdomino/': typeof KingdominoIndexRoute
  '/splendor/': typeof SplendorIndexRoute
  '/tictactoe/': typeof TictactoeIndexRoute
  '/wordle/': typeof WordleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callbreak/$gameId'
    | '/fish/$gameId'
    | '/kingdomino/$gameId'
    | '/splendor/$gameId'
    | '/tictactoe/$gameId'
    | '/wordle/$gameId'
    | '/callbreak/'
    | '/fish/'
    | '/kingdomino/'
    | '/splendor/'
    | '/tictactoe/'
    | '/wordle/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callbreak/$gameId'
    | '/fish/$gameId'
    | '/kingdomino/$gameId'
    | '/splendor/$gameId'
    | '/tictactoe/$gameId'
    | '/wordle/$gameId'
    | '/callbreak'
    | '/fish'
    | '/kingdomino'
    | '/splendor'
    | '/tictactoe'
    | '/wordle'
  id:
    | '__root__'
    | '/'
    | '/callbreak/$gameId'
    | '/fish/$gameId'
    | '/kingdomino/$gameId'
    | '/splendor/$gameId'
    | '/tictactoe/$gameId'
    | '/wordle/$gameId'
    | '/callbreak/'
    | '/fish/'
    | '/kingdomino/'
    | '/splendor/'
    | '/tictactoe/'
    | '/wordle/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbreakGameIdRoute: typeof CallbreakGameIdRoute
  FishGameIdRoute: typeof FishGameIdRoute
  KingdominoGameIdRoute: typeof KingdominoGameIdRoute
  SplendorGameIdRoute: typeof SplendorGameIdRoute
  TictactoeGameIdRoute: typeof TictactoeGameIdRoute
  WordleGameIdRoute: typeof WordleGameIdRoute
  CallbreakIndexRoute: typeof CallbreakIndexRoute
  FishIndexRoute: typeof FishIndexRoute
  KingdominoIndexRoute: typeof KingdominoIndexRoute
  SplendorIndexRoute: typeof SplendorIndexRoute
  TictactoeIndexRoute: typeof TictactoeIndexRoute
  WordleIndexRoute: typeof WordleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wordle/': {
      id: '/wordle/'
      path: '/wordle'
      fullPath: '/wordle/'
      preLoaderRoute: typeof WordleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tictactoe/': {
      id: '/tictactoe/'
      path: '/tictactoe'
      fullPath: '/tictactoe/'
      preLoaderRoute: typeof TictactoeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splendor/': {
      id: '/splendor/'
      path: '/splendor'
      fullPath: '/splendor/'
      preLoaderRoute: typeof SplendorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kingdomino/': {
      id: '/kingdomino/'
      path: '/kingdomino'
      fullPath: '/kingdomino/'
      preLoaderRoute: typeof KingdominoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish/': {
      id: '/fish/'
      path: '/fish'
      fullPath: '/fish/'
      preLoaderRoute: typeof FishIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callbreak/': {
      id: '/callbreak/'
      path: '/callbreak'
      fullPath: '/callbreak/'
      preLoaderRoute: typeof CallbreakIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wordle/$gameId': {
      id: '/wordle/$gameId'
      path: '/wordle/$gameId'
      fullPath: '/wordle/$gameId'
      preLoaderRoute: typeof WordleGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tictactoe/$gameId': {
      id: '/tictactoe/$gameId'
      path: '/tictactoe/$gameId'
      fullPath: '/tictactoe/$gameId'
      preLoaderRoute: typeof TictactoeGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splendor/$gameId': {
      id: '/splendor/$gameId'
      path: '/splendor/$gameId'
      fullPath: '/splendor/$gameId'
      preLoaderRoute: typeof SplendorGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kingdomino/$gameId': {
      id: '/kingdomino/$gameId'
      path: '/kingdomino/$gameId'
      fullPath: '/kingdomino/$gameId'
      preLoaderRoute: typeof KingdominoGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish/$gameId': {
      id: '/fish/$gameId'
      path: '/fish/$gameId'
      fullPath: '/fish/$gameId'
      preLoaderRoute: typeof FishGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callbreak/$gameId': {
      id: '/callbreak/$gameId'
      path: '/callbreak/$gameId'
      fullPath: '/callbreak/$gameId'
      preLoaderRoute: typeof CallbreakGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbreakGameIdRoute: CallbreakGameIdRoute,
  FishGameIdRoute: FishGameIdRoute,
  KingdominoGameIdRoute: KingdominoGameIdRoute,
  SplendorGameIdRoute: SplendorGameIdRoute,
  TictactoeGameIdRoute: TictactoeGameIdRoute,
  WordleGameIdRoute: WordleGameIdRoute,
  CallbreakIndexRoute: CallbreakIndexRoute,
  FishIndexRoute: FishIndexRoute,
  KingdominoIndexRoute: KingdominoIndexRoute,
  SplendorIndexRoute: SplendorIndexRoute,
  TictactoeIndexRoute: TictactoeIndexRoute,
  WordleIndexRoute: WordleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
