/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FishRouteImport } from './routes/fish'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WordleIndexRouteImport } from './routes/wordle.index'
import { Route as CallbreakIndexRouteImport } from './routes/callbreak.index'
import { Route as WordleGameIdRouteImport } from './routes/wordle.$gameId'
import { Route as FishGameIdRouteImport } from './routes/fish.$gameId'
import { Route as CallbreakGameIdRouteImport } from './routes/callbreak.$gameId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FishRoute = FishRouteImport.update({
  id: '/fish',
  path: '/fish',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordleIndexRoute = WordleIndexRouteImport.update({
  id: '/wordle/',
  path: '/wordle/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbreakIndexRoute = CallbreakIndexRouteImport.update({
  id: '/callbreak/',
  path: '/callbreak/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordleGameIdRoute = WordleGameIdRouteImport.update({
  id: '/wordle/$gameId',
  path: '/wordle/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const FishGameIdRoute = FishGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => FishRoute,
} as any)
const CallbreakGameIdRoute = CallbreakGameIdRouteImport.update({
  id: '/callbreak/$gameId',
  path: '/callbreak/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fish': typeof FishRouteWithChildren
  '/settings': typeof SettingsRoute
  '/callbreak/$gameId': typeof CallbreakGameIdRoute
  '/fish/$gameId': typeof FishGameIdRoute
  '/wordle/$gameId': typeof WordleGameIdRoute
  '/callbreak': typeof CallbreakIndexRoute
  '/wordle': typeof WordleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fish': typeof FishRouteWithChildren
  '/settings': typeof SettingsRoute
  '/callbreak/$gameId': typeof CallbreakGameIdRoute
  '/fish/$gameId': typeof FishGameIdRoute
  '/wordle/$gameId': typeof WordleGameIdRoute
  '/callbreak': typeof CallbreakIndexRoute
  '/wordle': typeof WordleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fish': typeof FishRouteWithChildren
  '/settings': typeof SettingsRoute
  '/callbreak/$gameId': typeof CallbreakGameIdRoute
  '/fish/$gameId': typeof FishGameIdRoute
  '/wordle/$gameId': typeof WordleGameIdRoute
  '/callbreak/': typeof CallbreakIndexRoute
  '/wordle/': typeof WordleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fish'
    | '/settings'
    | '/callbreak/$gameId'
    | '/fish/$gameId'
    | '/wordle/$gameId'
    | '/callbreak'
    | '/wordle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fish'
    | '/settings'
    | '/callbreak/$gameId'
    | '/fish/$gameId'
    | '/wordle/$gameId'
    | '/callbreak'
    | '/wordle'
  id:
    | '__root__'
    | '/'
    | '/fish'
    | '/settings'
    | '/callbreak/$gameId'
    | '/fish/$gameId'
    | '/wordle/$gameId'
    | '/callbreak/'
    | '/wordle/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FishRoute: typeof FishRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  CallbreakGameIdRoute: typeof CallbreakGameIdRoute
  WordleGameIdRoute: typeof WordleGameIdRoute
  CallbreakIndexRoute: typeof CallbreakIndexRoute
  WordleIndexRoute: typeof WordleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish': {
      id: '/fish'
      path: '/fish'
      fullPath: '/fish'
      preLoaderRoute: typeof FishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wordle/': {
      id: '/wordle/'
      path: '/wordle'
      fullPath: '/wordle'
      preLoaderRoute: typeof WordleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callbreak/': {
      id: '/callbreak/'
      path: '/callbreak'
      fullPath: '/callbreak'
      preLoaderRoute: typeof CallbreakIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wordle/$gameId': {
      id: '/wordle/$gameId'
      path: '/wordle/$gameId'
      fullPath: '/wordle/$gameId'
      preLoaderRoute: typeof WordleGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish/$gameId': {
      id: '/fish/$gameId'
      path: '/$gameId'
      fullPath: '/fish/$gameId'
      preLoaderRoute: typeof FishGameIdRouteImport
      parentRoute: typeof FishRoute
    }
    '/callbreak/$gameId': {
      id: '/callbreak/$gameId'
      path: '/callbreak/$gameId'
      fullPath: '/callbreak/$gameId'
      preLoaderRoute: typeof CallbreakGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FishRouteChildren {
  FishGameIdRoute: typeof FishGameIdRoute
}

const FishRouteChildren: FishRouteChildren = {
  FishGameIdRoute: FishGameIdRoute,
}

const FishRouteWithChildren = FishRoute._addFileChildren(FishRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FishRoute: FishRouteWithChildren,
  SettingsRoute: SettingsRoute,
  CallbreakGameIdRoute: CallbreakGameIdRoute,
  WordleGameIdRoute: WordleGameIdRoute,
  CallbreakIndexRoute: CallbreakIndexRoute,
  WordleIndexRoute: WordleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
