/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordleRouteImport } from './routes/wordle'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FishRouteImport } from './routes/fish'
import { Route as CallbreakRouteImport } from './routes/callbreak'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WordleGameIdRouteImport } from './routes/wordle.$gameId'
import { Route as FishGameIdRouteImport } from './routes/fish.$gameId'
import { Route as CallbreakGameIdRouteImport } from './routes/callbreak.$gameId'

const WordleRoute = WordleRouteImport.update({
  id: '/wordle',
  path: '/wordle',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FishRoute = FishRouteImport.update({
  id: '/fish',
  path: '/fish',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbreakRoute = CallbreakRouteImport.update({
  id: '/callbreak',
  path: '/callbreak',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordleGameIdRoute = WordleGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => WordleRoute,
} as any)
const FishGameIdRoute = FishGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => FishRoute,
} as any)
const CallbreakGameIdRoute = CallbreakGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => CallbreakRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callbreak': typeof CallbreakRouteWithChildren
  '/fish': typeof FishRouteWithChildren
  '/settings': typeof SettingsRoute
  '/wordle': typeof WordleRouteWithChildren
  '/callbreak/$gameId': typeof CallbreakGameIdRoute
  '/fish/$gameId': typeof FishGameIdRoute
  '/wordle/$gameId': typeof WordleGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callbreak': typeof CallbreakRouteWithChildren
  '/fish': typeof FishRouteWithChildren
  '/settings': typeof SettingsRoute
  '/wordle': typeof WordleRouteWithChildren
  '/callbreak/$gameId': typeof CallbreakGameIdRoute
  '/fish/$gameId': typeof FishGameIdRoute
  '/wordle/$gameId': typeof WordleGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callbreak': typeof CallbreakRouteWithChildren
  '/fish': typeof FishRouteWithChildren
  '/settings': typeof SettingsRoute
  '/wordle': typeof WordleRouteWithChildren
  '/callbreak/$gameId': typeof CallbreakGameIdRoute
  '/fish/$gameId': typeof FishGameIdRoute
  '/wordle/$gameId': typeof WordleGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callbreak'
    | '/fish'
    | '/settings'
    | '/wordle'
    | '/callbreak/$gameId'
    | '/fish/$gameId'
    | '/wordle/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callbreak'
    | '/fish'
    | '/settings'
    | '/wordle'
    | '/callbreak/$gameId'
    | '/fish/$gameId'
    | '/wordle/$gameId'
  id:
    | '__root__'
    | '/'
    | '/callbreak'
    | '/fish'
    | '/settings'
    | '/wordle'
    | '/callbreak/$gameId'
    | '/fish/$gameId'
    | '/wordle/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbreakRoute: typeof CallbreakRouteWithChildren
  FishRoute: typeof FishRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  WordleRoute: typeof WordleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wordle': {
      id: '/wordle'
      path: '/wordle'
      fullPath: '/wordle'
      preLoaderRoute: typeof WordleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish': {
      id: '/fish'
      path: '/fish'
      fullPath: '/fish'
      preLoaderRoute: typeof FishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callbreak': {
      id: '/callbreak'
      path: '/callbreak'
      fullPath: '/callbreak'
      preLoaderRoute: typeof CallbreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wordle/$gameId': {
      id: '/wordle/$gameId'
      path: '/$gameId'
      fullPath: '/wordle/$gameId'
      preLoaderRoute: typeof WordleGameIdRouteImport
      parentRoute: typeof WordleRoute
    }
    '/fish/$gameId': {
      id: '/fish/$gameId'
      path: '/$gameId'
      fullPath: '/fish/$gameId'
      preLoaderRoute: typeof FishGameIdRouteImport
      parentRoute: typeof FishRoute
    }
    '/callbreak/$gameId': {
      id: '/callbreak/$gameId'
      path: '/$gameId'
      fullPath: '/callbreak/$gameId'
      preLoaderRoute: typeof CallbreakGameIdRouteImport
      parentRoute: typeof CallbreakRoute
    }
  }
}

interface CallbreakRouteChildren {
  CallbreakGameIdRoute: typeof CallbreakGameIdRoute
}

const CallbreakRouteChildren: CallbreakRouteChildren = {
  CallbreakGameIdRoute: CallbreakGameIdRoute,
}

const CallbreakRouteWithChildren = CallbreakRoute._addFileChildren(
  CallbreakRouteChildren,
)

interface FishRouteChildren {
  FishGameIdRoute: typeof FishGameIdRoute
}

const FishRouteChildren: FishRouteChildren = {
  FishGameIdRoute: FishGameIdRoute,
}

const FishRouteWithChildren = FishRoute._addFileChildren(FishRouteChildren)

interface WordleRouteChildren {
  WordleGameIdRoute: typeof WordleGameIdRoute
}

const WordleRouteChildren: WordleRouteChildren = {
  WordleGameIdRoute: WordleGameIdRoute,
}

const WordleRouteWithChildren =
  WordleRoute._addFileChildren(WordleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbreakRoute: CallbreakRouteWithChildren,
  FishRoute: FishRouteWithChildren,
  SettingsRoute: SettingsRoute,
  WordleRoute: WordleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
