/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WordleIndexRouteImport } from './routes/wordle.index'
import { Route as TictactoeIndexRouteImport } from './routes/tictactoe.index'
import { Route as SplendorIndexRouteImport } from './routes/splendor.index'
import { Route as FishIndexRouteImport } from './routes/fish.index'
import { Route as WordleMatchIdRouteImport } from './routes/wordle.$matchId'
import { Route as TictactoeMatchIdRouteImport } from './routes/tictactoe.$matchId'
import { Route as SyncSplatRouteImport } from './routes/sync.$'
import { Route as SplendorMatchIdRouteImport } from './routes/splendor.$matchId'
import { Route as FishMatchIdRouteImport } from './routes/fish.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordleIndexRoute = WordleIndexRouteImport.update({
  id: '/wordle/',
  path: '/wordle/',
  getParentRoute: () => rootRouteImport,
} as any)
const TictactoeIndexRoute = TictactoeIndexRouteImport.update({
  id: '/tictactoe/',
  path: '/tictactoe/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplendorIndexRoute = SplendorIndexRouteImport.update({
  id: '/splendor/',
  path: '/splendor/',
  getParentRoute: () => rootRouteImport,
} as any)
const FishIndexRoute = FishIndexRouteImport.update({
  id: '/fish/',
  path: '/fish/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordleMatchIdRoute = WordleMatchIdRouteImport.update({
  id: '/wordle/$matchId',
  path: '/wordle/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const TictactoeMatchIdRoute = TictactoeMatchIdRouteImport.update({
  id: '/tictactoe/$matchId',
  path: '/tictactoe/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncSplatRoute = SyncSplatRouteImport.update({
  id: '/sync/$',
  path: '/sync/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SplendorMatchIdRoute = SplendorMatchIdRouteImport.update({
  id: '/splendor/$matchId',
  path: '/splendor/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const FishMatchIdRoute = FishMatchIdRouteImport.update({
  id: '/fish/$matchId',
  path: '/fish/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fish/$matchId': typeof FishMatchIdRoute
  '/splendor/$matchId': typeof SplendorMatchIdRoute
  '/sync/$': typeof SyncSplatRoute
  '/tictactoe/$matchId': typeof TictactoeMatchIdRoute
  '/wordle/$matchId': typeof WordleMatchIdRoute
  '/fish/': typeof FishIndexRoute
  '/splendor/': typeof SplendorIndexRoute
  '/tictactoe/': typeof TictactoeIndexRoute
  '/wordle/': typeof WordleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fish/$matchId': typeof FishMatchIdRoute
  '/splendor/$matchId': typeof SplendorMatchIdRoute
  '/sync/$': typeof SyncSplatRoute
  '/tictactoe/$matchId': typeof TictactoeMatchIdRoute
  '/wordle/$matchId': typeof WordleMatchIdRoute
  '/fish': typeof FishIndexRoute
  '/splendor': typeof SplendorIndexRoute
  '/tictactoe': typeof TictactoeIndexRoute
  '/wordle': typeof WordleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fish/$matchId': typeof FishMatchIdRoute
  '/splendor/$matchId': typeof SplendorMatchIdRoute
  '/sync/$': typeof SyncSplatRoute
  '/tictactoe/$matchId': typeof TictactoeMatchIdRoute
  '/wordle/$matchId': typeof WordleMatchIdRoute
  '/fish/': typeof FishIndexRoute
  '/splendor/': typeof SplendorIndexRoute
  '/tictactoe/': typeof TictactoeIndexRoute
  '/wordle/': typeof WordleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fish/$matchId'
    | '/splendor/$matchId'
    | '/sync/$'
    | '/tictactoe/$matchId'
    | '/wordle/$matchId'
    | '/fish/'
    | '/splendor/'
    | '/tictactoe/'
    | '/wordle/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fish/$matchId'
    | '/splendor/$matchId'
    | '/sync/$'
    | '/tictactoe/$matchId'
    | '/wordle/$matchId'
    | '/fish'
    | '/splendor'
    | '/tictactoe'
    | '/wordle'
  id:
    | '__root__'
    | '/'
    | '/fish/$matchId'
    | '/splendor/$matchId'
    | '/sync/$'
    | '/tictactoe/$matchId'
    | '/wordle/$matchId'
    | '/fish/'
    | '/splendor/'
    | '/tictactoe/'
    | '/wordle/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FishMatchIdRoute: typeof FishMatchIdRoute
  SplendorMatchIdRoute: typeof SplendorMatchIdRoute
  SyncSplatRoute: typeof SyncSplatRoute
  TictactoeMatchIdRoute: typeof TictactoeMatchIdRoute
  WordleMatchIdRoute: typeof WordleMatchIdRoute
  FishIndexRoute: typeof FishIndexRoute
  SplendorIndexRoute: typeof SplendorIndexRoute
  TictactoeIndexRoute: typeof TictactoeIndexRoute
  WordleIndexRoute: typeof WordleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wordle/': {
      id: '/wordle/'
      path: '/wordle'
      fullPath: '/wordle/'
      preLoaderRoute: typeof WordleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tictactoe/': {
      id: '/tictactoe/'
      path: '/tictactoe'
      fullPath: '/tictactoe/'
      preLoaderRoute: typeof TictactoeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splendor/': {
      id: '/splendor/'
      path: '/splendor'
      fullPath: '/splendor/'
      preLoaderRoute: typeof SplendorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish/': {
      id: '/fish/'
      path: '/fish'
      fullPath: '/fish/'
      preLoaderRoute: typeof FishIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wordle/$matchId': {
      id: '/wordle/$matchId'
      path: '/wordle/$matchId'
      fullPath: '/wordle/$matchId'
      preLoaderRoute: typeof WordleMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tictactoe/$matchId': {
      id: '/tictactoe/$matchId'
      path: '/tictactoe/$matchId'
      fullPath: '/tictactoe/$matchId'
      preLoaderRoute: typeof TictactoeMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync/$': {
      id: '/sync/$'
      path: '/sync/$'
      fullPath: '/sync/$'
      preLoaderRoute: typeof SyncSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splendor/$matchId': {
      id: '/splendor/$matchId'
      path: '/splendor/$matchId'
      fullPath: '/splendor/$matchId'
      preLoaderRoute: typeof SplendorMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish/$matchId': {
      id: '/fish/$matchId'
      path: '/fish/$matchId'
      fullPath: '/fish/$matchId'
      preLoaderRoute: typeof FishMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FishMatchIdRoute: FishMatchIdRoute,
  SplendorMatchIdRoute: SplendorMatchIdRoute,
  SyncSplatRoute: SyncSplatRoute,
  TictactoeMatchIdRoute: TictactoeMatchIdRoute,
  WordleMatchIdRoute: WordleMatchIdRoute,
  FishIndexRoute: FishIndexRoute,
  SplendorIndexRoute: SplendorIndexRoute,
  TictactoeIndexRoute: TictactoeIndexRoute,
  WordleIndexRoute: WordleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
