name: Nx Standard Use Case
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.8.0
      - run: pnpm install
      - run: pnpm nx affected --target=test --all --parallel

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.8.0
      - run: pnpm install
      - run: pnpm nx affected --target=build --all --prod --parallel